# Generated by Django 6.0.4 on 2026-04-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_race', models.CharField(max_length=100)),
                ('flight_date', models.CharField(max_length=50)),
                ('flight_time', models.CharField(max_length=50)),
                ('from_city', models.CharField(max_length=25)),
                ('to_city', models.CharField(max_length=25)),
                ('aircraft_id', models.IntegerField(null=True)),
                ('bookings_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'flights',
            },
        ),
    ]
