# Generated by Django 6.0.4 on 2026-04-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('models', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'aircraft',
            },
        ),
    ]
