# Generated by Django 6.0.4 on 2026-04-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flights_id', models.IntegerField(null=True)),
                ('username', models.CharField(max_length=50)),
                ('passport', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=9)),
                ('payments_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
